
export enum AppointmentStatus {
  AVAILABLE = 'AVAILABLE',
  BOOKED = 'BOOKED',
  COMPLETED = 'COMPLETED',
  PENDING_APPROVAL = 'PENDING_APPROVAL'
}

export type SessionType = 'IN_PERSON' | 'VIDEO';

export interface TimeSlot {
  id: string;
  date: string; // ISO Date string YYYY-MM-DD
  time: string; // HH:mm format
  status: AppointmentStatus;
  clientName?: string;
  clientEmail?: string;
  clientPhone?: string; // New: Mobile phone for SMS
  clientNote?: string;
  aiSummary?: string; // Generated by Gemini
  sessionType?: SessionType;
  privateNotes?: string; // New: Private notes for the therapist
}

export interface ServiceItem {
  title: string;
  description: string;
  duration: string;
  price: string;
}
